image: ruby

pages:
  script:
  - gem install compass zurb-foundation # CSS stylesheets generation
  - gem install prawn -v 2.1.0
  - gem install asciidoctor # HTML generation
  - asciidoctor mon_doc.adoc -o index.html
  - asciidoctor-pdf mon_doc.adoc -o mon_bouquin.pdf


# rajoutez ici la génération du index.html ainsi que du fichier pdf
# dans un sous-répertoire que vous nommerez "public"

  artifacts:
    paths:
    - public

  only:
  - master